-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 18:38:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stavkova
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `stavkova` ;

-- -----------------------------------------------------
-- Schema stavkova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stavkova` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `stavkova` ;

-- -----------------------------------------------------
-- Table `stavkova`.`sport_events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stavkova`.`sport_events` ;

CREATE TABLE IF NOT EXISTS `stavkova`.`sport_events` (
                                                         `event_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                         `event_name` VARCHAR(100) NOT NULL,
    `start_time` DATETIME NOT NULL,
    `sport_type` VARCHAR(50) NOT NULL,
    `status` ENUM('upcoming', 'finished') NOT NULL,
    PRIMARY KEY (`event_id`),
    UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stavkova`.`possible_outcomes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stavkova`.`possible_outcomes` ;

CREATE TABLE IF NOT EXISTS `stavkova`.`possible_outcomes` (
                                                              `outcome_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                              `event_id` BIGINT NOT NULL,
                                                              `result_name` VARCHAR(50) NOT NULL,
    `odds` DECIMAL(5,2) NOT NULL,
    `status` ENUM("winning", "loosing") NULL,
    PRIMARY KEY (`outcome_id`),
    INDEX `event_id` (`event_id` ASC) VISIBLE,
    UNIQUE INDEX `outcome_id_UNIQUE` (`outcome_id` ASC) VISIBLE,
    CONSTRAINT `result_ibfk_1`
    FOREIGN KEY (`event_id`)
    REFERENCES `stavkova`.`sport_events` (`event_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stavkova`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stavkova`.`users` ;

CREATE TABLE IF NOT EXISTS `stavkova`.`users` (
                                                  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                  `username` VARCHAR(50) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `role` ENUM('user', 'admin') NOT NULL,
    PRIMARY KEY (`user_id`),
    UNIQUE INDEX `username` (`username` ASC) VISIBLE,
    UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stavkova`.`statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stavkova`.`statistics` ;

CREATE TABLE IF NOT EXISTS `stavkova`.`statistics` (
                                                       `statistic_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                       `user_id` BIGINT NOT NULL,
                                                       `total_bets` INT NOT NULL DEFAULT 0,
                                                       `total_stakes` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `total_winnings` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `win_rate` DECIMAL(3,2) NOT NULL DEFAULT 0,
    `average_bet` DECIMAL(10,2) NOT NULL DEFAULT 0,
    `max_bet` DECIMAL(10,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (`statistic_id`, `user_id`),
    UNIQUE INDEX `statistic_id_UNIQUE` (`statistic_id` ASC) VISIBLE,
    INDEX `fk_statistic_users1_idx` (`user_id` ASC) VISIBLE,
    CONSTRAINT `fk_statistic_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stavkova`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `stavkova`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stavkova`.`tickets` ;

CREATE TABLE IF NOT EXISTS `stavkova`.`tickets` (
                                                    `ticket_id` BIGINT NOT NULL AUTO_INCREMENT,
                                                    `user_id` BIGINT NOT NULL,
                                                    `outcome_id` BIGINT NOT NULL,
                                                    `stake` DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (`ticket_id`),
    INDEX `user_id` (`user_id` ASC) VISIBLE,
    INDEX `result_id` (`outcome_id` ASC) VISIBLE,
    UNIQUE INDEX `ticket_id_UNIQUE` (`ticket_id` ASC) VISIBLE,
    CONSTRAINT `ticket_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `stavkova`.`users` (`user_id`),
    CONSTRAINT `ticket_ibfk_3`
    FOREIGN KEY (`outcome_id`)
    REFERENCES `stavkova`.`possible_outcomes` (`outcome_id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `stavkova`.`users` (`username`, `password`, `email`, `balance`, `role`) VALUES
                                                                                        ('john_doe', 'password123', 'john.doe@example.com', 100.00, 'user'),
                                                                                        ('jane_smith', 'password456', 'jane.smith@example.com', 250.50, 'user'),
                                                                                        ('admin', 'adminpass', 'admin@example.com', 500.00, 'admin');

INSERT INTO `stavkova`.`sport_events` (`event_name`, `start_time`, `sport_type`, `status`) VALUES
                                                                                               ('Champions League Final', '2024-11-20 20:00:00', 'Football', 'upcoming'),
                                                                                               ('NBA Finals Game 7', '2024-11-22 19:30:00', 'Basketball', 'upcoming'),
                                                                                               ('Wimbledon Mens Final', '2024-07-10 14:00:00', 'Tennis', 'finished'),
    ('Super Bowl', '2024-02-04 18:30:00', 'American Football', 'finished');

INSERT INTO `stavkova`.`possible_outcomes` (`event_id`, `result_name`, `odds`, `status`) VALUES
    (1, 'Team A wins', 1.85, NULL),
    (1, 'Team B wins', 2.10, NULL),
    (2, 'Team X wins', 1.75, NULL),
    (2, 'Team Y wins', 2.20, NULL),
    (3, 'Player A wins', 1.50, 'winning'),
    (3, 'Player B wins', 2.50, 'loosing'),
    (4, 'Team A wins', 1.60, 'winning'),
    (4, 'Team B wins', 2.40, 'loosing');

INSERT INTO `stavkova`.`statistics` (`user_id`, `total_bets`, `total_stakes`, `total_winnings`, `win_rate`, `average_bet`, `max_bet`) VALUES
    (1, 15, 150.00, 120.00, 0.75, 10.00, 25.00),
    (2, 20, 200.00, 180.00, 0.85, 10.00, 30.00);

INSERT INTO `stavkova`.`tickets` (`user_id`, `outcome_id`, `stake`) VALUES
    (1, 1, 20.00),
    (1, 3, 15.00),
    (2, 5, 50.00),
    (2, 7, 30.00);


